### ISSUE TITLE
Allow using node-based IAM credentials

### ISSUE THREAD

**Issue by mikekap** [openai/kubernetes-ec2-autoscaler#13]
This is especially useful if you're using something like kube2iam that gives each pod their own IAM identity. Right now the AWS_* environment/command line variables are required.

**Comment by alexouzounis** [comment]
haven't tried the autoscaler yet - planning to do some testing next week but those were my thoughts as well. Since its using boto i would expect to work as is if you define an IAM policy and pass it to the pod using kube2iam. 

Have you tried that ?

**Comment by preflightsiren** [comment]
it won't start up; https://github.com/openai/kubernetes-ec2-autoscaler/blob/master/main.py#L53

**Comment by esigler** [comment]
Howdy! This repo is being archived, and no longer accepting feature requests.  Thanks!
