### ISSUE TITLE
Documentation request: Document differences between this and auto-scalar from k8s

### ISSUE THREAD

**Issue by ryanwalls** [openai/kubernetes-ec2-autoscaler#22]
Kubernetes has an auto scalar in their main repo.  https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler.  It would be nice to document the differences between the two.  Currently it is not clear to me what the feature differences are and why you had to create your own auto-scalar.

**Comment by r4j4h** [comment]
I think I can answer the latter question, the contrib variant wasn't around for AWS [until recently](https://github.com/kubernetes/kubernetes/issues/11935#issuecomment-268845320).

I totally agree some comparison docs would be great. I will try to contribute some if I can find the time and no one else has by then!

Here's a sketch summary of what I know right now:

- IAM User in thisrepo uses "autoscaling:DescribeLaunchConfigurations" while contrib does not
- contrib calls out several kube-system namespace protections from being scaled down, this repo does not mention it and a cursory github search only revealed an issue re: reading secrets in a cluster.
- This repo mentions it is designed for batch jobs, both repos appear to poll for configurable intervals
- This repo supports multiple regions but does not mention availability zones within them while the contrib specifically mentions it does not support multiple regions or multiple availability zones and instead currently suggests [dedicating an ASG per AZ and scaling each](https://github.com/coreos/coreos-kubernetes/issues/668#issuecomment-247189035)

**Comment by esigler** [comment]
Howdy! This repo is being archived, and no longer accepting feature requests.  Thanks!
