### ISSUE TITLE
Not draining nodes that are running kube-proxy

### ISSUE THREAD

**Issue by shaunokeefe** [openai/kubernetes-ec2-autoscaler#23]
G'day,

I've got nodes that are running at 0% CPU that I'm expecting to have deleted during maintenance. When the cluster `scale_loop()` runs and the subsequent call to `maintain()` is made, the node's status comes back as `UNDER_UTILIZED_UNDRAINABLE`. 

Stepping through the code, I can see that this is due to the kube-proxy pod running on the node.

The node is marked as undrainable here (in the `maintain` method): 

```
undrainable_list = [p for p in node_pods if not p.is_drainable()]
[...]
drainable = not undrainable_list
```

This is due to the kube-proxy pod returning  `{}` (logically False?) for its `is_replicated` method.
 
```
def is_drainable(self):
    return self.is_replicated() and not self.is_critical() and not self.is_in_drain_grace_period()
```

My understanding is that `kube-proxy` runs on all nodes and that the code as it is would never successfully delete nodes and scale in ASGs as the kube-proxy pod is always present and will always return `false` for `is_drainable`.

Am I missing something in my setup or does this look like a bug?

**Comment by shaunokeefe** [comment]
Just a note. This might be due to our two deploys having kube-proxy installed in different ways? I'm using Kops which I _think_ installs kube-proxy via a manifest (i.e. not a daemonset or a replication controller). So although it's a candidate for being drained, the same as any daemonset, it doesn't get a `created-by` tag and accordingly returns `False` for the `is_drainable` method.

**Comment by jkinkead** [comment]
We have a workaround-patch: https://github.com/allenai/kubernetes-ec2-autoscaler/pull/7

This lets you specify `--drainable-labels k8s-app=kube-proxy` on the commandline and have the autoscaler drain the kops-created kube-proxy pods.

I don't especially like the implementation at the moment. If I clean it up, I'll merge upstream.

**Comment by vpm-bradleyhession** [comment]
Please can we merge this upstream?

**Comment by cberner** [comment]
How are you deploying kube-proxy? If you're deploying it as a pod, I think a DaemonSet should solve this

**Comment by philovivero** [comment]
Is there any resolution to this? I'm hitting this problem. Every Node runs a kube-proxy. It seems weird to say, essentially, `--force` is required for the `drain` to ever work in some common configurations.

**Comment by esigler** [comment]
Howdy! This repo is being archived, and no longer accepting bug reports.  Thanks!
