### ISSUE TITLE
Scale up for certain pods only.

### ISSUE THREAD

**Issue by ca16** [openai/kubernetes-ec2-autoscaler#56]
Hi all,

For our Kubernetes cluster, it would be really handy to be able to specify that we only want the autoscaler to scale up for certain pending pods. 

Is this functionality that you are thinking about adding? We've put together a basic version of this (only pods with the given label are considered) built on your autoscaler for ourselves [here](https://github.com/allenai/kubernetes-ec2-autoscaler/pull/2), if you're interested.

A little more on our setup/why this would be helpful for us:
We want to be able to scale different ASGs separately. We have different kinds of tasks running on different kinds of nodes, and we don't want nodes of type A to get added to support tasks that should go on nodes of type B, even if they would fit on nodes of type A. We've found that the [Kubernetes autoscaler](https://github.com/kubernetes/autoscaler) covers a lot of this, except for the fact that it does not allow the minimum size of ASGs to fall below 1. This is where we find your autoscaler quite helpful.

Thanks!

**Comment by esigler** [comment]
Howdy! This repo is being archived, and no longer accepting feature requests.  Thanks!
