### ISSUE TITLE
ec2 specificity -- would you open this up to other clouds?

### ISSUE THREAD

**Issue by zfrenchee** [openai/kubernetes-ec2-autoscaler#6]
Hello OpenAI developers! 
Thanks for this terrific project. It's inspiring and useful work! I'm quite interested in this work, but for our purposes, we'd like to use a different cloud provider which has granted us research credits. Is there some way this work could be abstracted to provide the same functionality across multiple clouds? Would that ever be something the original developers of that project would be interested in contributing to?

**Comment by koolay** [comment]
+1

**Comment by yaroslavvb** [comment]
+cc @jonasschneider

**Comment by jonasschneider** [comment]
Yep, we're working on this -- more details soon :)

**Comment by zfrenchee** [comment]
@jonasschneider bump.
