### ISSUE TITLE
Azure support documentation?

### ISSUE THREAD

**Issue by doprdele** [openai/kubernetes-ec2-autoscaler#81]
Hi,

I was wondering if there was any documentation on how to setup Azure autoscaling in the azure branch. All I see now is EC2 autoscaling.

Best,
Evan

**Comment by cristipp** [comment]
Also interested in GCP support. The standard GKE autoscaler [0] is a bit too unflexible for our [scrappy] needs.

[0] https://cloud.google.com/container-engine/docs/cluster-autoscaler

**Comment by cristipp** [comment]
I've looked at the code, starting with https://github.com/openai/kubernetes-ec2-autoscaler/blob/master/test/test_cluster.py. Seems doable to support multiple cloud providers. 

The core abstraction point could be AutoScalingGroups. For example, a GKEAutoScalingGroups would simply use the the google-cloud-python [0] equivalent of the command line ```gcloud container clusters resize CLUSTER_NAME --size SIZE``` as its core API dependency.

For testing, we could abstract boto3.client as BotoCloudClient, and run either:
* AwsAutoScalingGroups + BotoCloudClient + moto, to keep existing AWS tests unchanged.
* FakeAutoScalingGroups + FakeCloudClient, to test non AWS clusters like GKE. Alas, google-cloud-python doesn't offer a moto-equivalent library, so tests will exercise less functionality. OTOH, the cloud functionality is rather trivial, so it could work well in practice.

[0] https://github.com/GoogleCloudPlatform/google-cloud-python

**Comment by ianatha** [comment]
While supporting more cloud providers would be beneficial, at this time, this project only supports EC2 & Azure. We've switched to using cluster-autoscaler: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler, and are unable to provide support for this repository.

**Comment by posix4e** [comment]
Yea we just used that as well, so feel free to close this
