### ISSUE TITLE
Consider to merge fixing cordon/uncordon and add util_threshold as option

### ISSUE THREAD

**Issue by overskylab** [openai/kubernetes-ec2-autoscaler#94]
From this PR
https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler/pull/48/files?diff=split

Currently, I have problem about scaling down 

Logging
```
2018-02-27T17:57:57+0000 - autoscaler.cluster - INFO - node: xxx.compute.internal: i-xxxx 
({"beta.kubernetes.io/arch": "amd64", 
"beta.kubernetes.io/instance-type": "t2.medium", 
"beta.kubernetes.io/os": "linux", 
"failure-domain.beta.kubernetes.io/region": "ap-southeast-1", 
"failure-domain.beta.kubernetes.io/zone": "ap-southeast-1a", 
"kops.k8s.io/instancegroup": "nodes", 
"kubernetes.io/hostname": "xxx.compute.internal", 
"kubernetes.io/role": "node", 
"node-role.kubernetes.io/node": "", 
"openai/cordoned-by-autoscaler": "true"}) 
state: ClusterNodeState.UNDER_UTILIZED_UNDRAINABLE
```

From logging above, This node is cordoning pod while autoscaler script checking as interval and found `kube-dns` from this node have status as pending -> spawn new ec2 -> this node stuck on this state.

In this case, the PR consider `"ClusterNodeState.UNDER_UTILIZED_UNDRAINABLE"` state have action as cordon. I think it will solve this problem.

Beyond, the PR have adjust `util_threshold` as option that mean I can dynamic configuration if idle node have several kube-system service and use CPU more than 30% (small EC2 type)

Thank you

**Comment by esigler** [comment]
As this repo is now archived, we won't be merging any PRs.  Thanks!
