### ISSUE TITLE
Autoscaler does not scale down

### ISSUE THREAD

**Issue by nirbo** [openai/kubernetes-ec2-autoscaler#95]
Several days ago, I upgraded to the current version of autoscaler in the 'master' branch.
Since I started using the newer version, autoscaler scales up, however it does not scale down - at all.

The only change in my Kubernetes cluster was an upgrade from 1.7.11 to 1.8.8.

Below is the error message I'm seeing:
`2018-03-07T23:28:55+0000 - autoscaler.cluster - ERROR - TOO MANY NODES TO SCALE IN: 29, max allowed is 3`

I can't seem to find out why autoscaler isn't scaling down and would appreciate any assistance.

Thanks.

**Comment by cberner** [comment]
We added a flag `--max-scale-in-fraction` which defaults to 10%. If you change it to `1.0` you will get back the old behavior

**Comment by nirbo** [comment]
@cberner 

Thanks for the quick response.

I've done that and it resulted in autoscaler completely deleting my Kubernetes nodes, while keeping the AWS instances intact.

**Comment by cberner** [comment]
Hmm, unfortunately we no longer have clusters in AWS, so I don't have a way to test that. Were the nodes perhaps in a "NotReady" state? Very happy to take a patch, if you find a bug
